apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geth
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: geth
        image: ethereum/client-go:v1.13.5
        args:
          - "--metrics"
          - "--metrics.addr=0.0.0.0"
          - "--syncmode=light"