apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web3-api
  template:
    metadata:
      labels:
        app: web3-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: web3-api
        image: web3-api
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web3-api
spec:
  selector:
    app: web3-api
  ports:
    - port: 3000
      targetPort: 3000
