name: Web3 DevOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f blockchain-node/k8s-deployment.yaml
          kubectl apply -f monitoring/

      - name: Verify Deployment
        run: |
            kubectl rollout status deployment/geth-node -n default
            kubectl rollout status deployment/prometheus -n monitoring
            kubectl rollout status deployment/grafana -n monitoring
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          