name: Web3 DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Minikube
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker --memory=4096 --cpus=2
          minikube status

      - name: Verify Dockerfiles exist
        run: |
          ls -la blockchain-node/Dockerfile
          ls -la api/Dockerfile

      - name: Build Blockchain Node
        run: |
          eval $(minikube docker-env)
          docker build -t geth-node ./blockchain-node
          docker images

      - name: Build Web3 API
        run: |
          eval $(minikube docker-env)
          docker build -t web3-api ./api
          docker images

      - name: Create monitoring namespace
        run: kubectl apply -f monitoring/init/00-namespace.yaml

      - name: Deploy Monitoring Stack
        run: |
          kubectl apply -f monitoring/prometheus-config.yaml
          kubectl apply -f monitoring/grafana-dashboards.yaml
          kubectl apply -f monitoring/grafana-provisioning.yaml
          kubectl apply -f monitoring/grafana.yaml
          kubectl get all -n monitoring

      - name: Deploy Applications
        run: |
          kubectl apply -f blockchain-node/k8s-deployment.yaml
          kubectl apply -f api/k8s-deployment.yaml
          kubectl get all -A

      - name: Verify Deployments
        run: |
          kubectl rollout status deployment/geth-node -n default --timeout=90s
          kubectl rollout status deployment/prometheus -n monitoring --timeout=90s
          kubectl rollout status deployment/grafana -n monitoring --timeout=90s

      - name: Get Service URLs
        run: |
          echo "Geth Node RPC: $(minikube service geth-node --url -n default)"
          echo "Prometheus: $(minikube service prometheus --url -n monitoring)"
          echo "Grafana: $(minikube service grafana --url -n monitoring)"