name: Web3 DevOps Pipeline

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Minikube
      - name: Start Minikube
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq conntrack
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker
          minikube status

      # Build and deploy
      - name: Deploy Blockchain Stack
        run: |
          eval $(minikube docker-env)
          kubectl apply -f blockchain-node/k8s-deployment.yaml
          kubectl apply -f monitoring/
          kubectl get all -A