name: Web3 DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify Required Files
        run: |
          # Check for blockchain-node Dockerfile
          if [ ! -f "blockchain-node/Dockerfile" ]; then
            echo "::error::Missing blockchain-node/Dockerfile"
            exit 1
          fi
          
          # Create default API Dockerfile if missing
          if [ ! -f "api/Dockerfile" ]; then
            echo "::warning::Creating default api/Dockerfile"
            mkdir -p api
            cat << 'EOF' > api/Dockerfile
FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["node", "server.js"]
EOF
          fi
          
          # Verify files
          ls -la blockchain-node/Dockerfile api/Dockerfile

      # ... rest of your workflow steps ...